version: '2'

services:
    spring-boot:
        image: noxob/firebase-todo-app
        ports:
            - 8080:8080
        environment:
            - spring.cloud.gcp.firestore.project-id=todo-app-noxob
        restart: always
    frontend:
        image: noxob/demo-todoapp-ui
        ports:
            - 80:80
        restart: always